azure:
  store_build_artifacts: True
channels:
  sources:
    - conda-forge
  targets:
    - ["tiledb", "main"]
github:
  user_or_org: TileDB-Inc
  branch_name: main
  tooling_branch_name: main
provider:
  win_64: azure
skip_render:
  - LICENSE.txt
upload_on_branch: main
azure:
  build_id: 46
  user_or_org: TileDB-Inc
  project_name: CI
